version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sketchy_heroes
    volumes:
      - ./db-data/:/var/lib/postgresql/data

